-- Phase 2 Seed Script
-- Auto-generated by scripts/generate-phase2-sql.js

BEGIN;


-- Content Item for 'Introduction to Computers'
INSERT INTO public.content_items (id, unit_id, subject_id, topic_id, title, description, type, status, visibility)
VALUES (
  'b39f01c0-a11b-491b-a0cb-3ce36bf9ff44',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '05968c8c-2a26-4933-a021-e457681771fc',
  '551ddc7d-d0b2-42fd-8a82-90a1dc141d1a',
  'Introduction to Computers - Notes',
  'Comprehensive study material for Introduction to Computers',
  'note',
  'published',
  'public'
) ON CONFLICT DO NOTHING;

-- Note for 'Introduction to Computers'
INSERT INTO public.notes (id, unit_id, topic_id, title, slug, body, status, visibility, summary, sort_order)
VALUES (
  '0258b6c7-15c0-4aba-959f-7377d69ec938',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '551ddc7d-d0b2-42fd-8a82-90a1dc141d1a',
  'Introduction to Computers - Full Notes',
  'introduction-to-computers-full-notes',
  '
# Introduction to Computers

## Learning Objectives
- Understand the basic definition of a computer.
- Identify the core components that make up a computer system.
- Trace the flow of information through the IPO (Input-Process-Output) cycle.

## Introduction
A computer is an advanced electronic device that takes raw data as input from the user, processes it under the control of a set of instructions (called a program), produces a result (output), and saves it for future use. The word "computer" comes from the Latin word "computare", which means to calculate or compute.

## Core Concepts
At its fundamental level, every computer operates on the **IPO Cycle**:
1. **Input**: Data or instructions entered into the computer.
2. **Process**: The manipulation of data according to given instructions, primarily done by the Central Processing Unit (CPU).
3. **Output**: The processed data presented to the user as meaningful information.

## Important Definitions
- **Data**: Unprocessed, raw facts and figures. It has no inherent meaning until processed.
- **Information**: Data that has been processed, organized, and structured in a meaningful way.
- **Hardware**: The physical, tangible parts of a computer system.
- **Software**: The set of instructions, programs, or data that tell the computer what to do.

## Detailed Explanation
The computer acts as a data processing machine. It does not possess independent cognition; instead, it operates precisely based on programmed logic provided by human developers. When a user inputs data (for instance, typing numbers on a keyboard), the software instructs the hardware on how to manipulate that data. The CPU executes these instructions mathematically and logically, and the resulting processed data is outputted to a screen or printer. This systematic procedure is what makes computing reliable and reproducible.

## Examples
- **Input Example**: Scanning a barcode at a supermarket.
- **Process Example**: The computer looking up the barcode in the database and calculating the total price.
- **Output Example**: Printing the receipt for the customer.

## Key Points
- A computer is an electronic machine that processes raw data into meaningful information.
- It operates on the Input-Process-Output (IPO) model.
- Computers execute tasks based on programmed logic rather than independent thought.

## Quick Revision
Remember the IPO cycle: Input (raw data) $\rightarrow$ Process (CPU execution) $\rightarrow$ Output (meaningful information). Hardware is what you can touch; software is the instructions running on it.

## Practice Questions
1. Define a computer and explain the origin of the word.
2. Differentiate between data and information with an example.
3. Describe the IPO cycle using a real-world scenario.
',
  'published',
  'public',
  'Study notes covering Introduction to Computers',
  1
) ON CONFLICT DO NOTHING;

-- Quiz for 'Introduction to Computers'
INSERT INTO public.quizzes (id, unit_id, topic_id, title, slug, description, status, is_public, max_attempts, passing_pct, order_index, negative_marking)
VALUES (
  'fe5987a9-2e95-4fa3-b4b2-7b79d12e1969',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '551ddc7d-d0b2-42fd-8a82-90a1dc141d1a',
  'Quiz: Introduction to Computers',
  'quiz-introduction-to-computers',
  'Test your fundamental knowledge of what a computer is and how it processes data.',
  'published',
  true,
  10,
  40,
  1,
  false
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'd4ef3c87-cfd1-4c24-8afa-5eb1c3d9748a',
  'fe5987a9-2e95-4fa3-b4b2-7b79d12e1969',
  'What does the IPO cycle stand for?',
  'The fundamental operation of a computer is based on Input, Process, and Output.',
  'single',
  1,
  1,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'e713403f-3052-427c-b893-f698deda083d',
  'd4ef3c87-cfd1-4c24-8afa-5eb1c3d9748a',
  'Information-Processing-Output',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '68abce28-abdd-4d2a-b384-6493f453f978',
  'd4ef3c87-cfd1-4c24-8afa-5eb1c3d9748a',
  'Input-Process-Output',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'd4c99ac3-ce0e-4f21-bf4d-61eba8f07c44',
  'd4ef3c87-cfd1-4c24-8afa-5eb1c3d9748a',
  'Input-Program-Output',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '661747ce-e821-43ae-91a9-80fa8e2a883c',
  'd4ef3c87-cfd1-4c24-8afa-5eb1c3d9748a',
  'Instruction-Process-Operation',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'c80a0d03-cbbf-41a1-8804-9b7781414ae9',
  'fe5987a9-2e95-4fa3-b4b2-7b79d12e1969',
  'Which of the following best describes ''Information''?',
  'Information is processed data that has meaning and context.',
  'single',
  1,
  2,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '98100c92-b951-4197-92ef-c20b794aa0d9',
  'c80a0d03-cbbf-41a1-8804-9b7781414ae9',
  'Raw facts and figures',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'b5a263a4-01e2-4ca0-bca4-0c939d093f5e',
  'c80a0d03-cbbf-41a1-8804-9b7781414ae9',
  'The physical components of a computer',
  false,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '687c9aeb-d4d6-4af8-a6ac-54f8a488a8ae',
  'c80a0d03-cbbf-41a1-8804-9b7781414ae9',
  'Processed data that is meaningful',
  true,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '20e3ec18-814b-4e65-907d-eeb81369eb1b',
  'c80a0d03-cbbf-41a1-8804-9b7781414ae9',
  'A set of instructions given to the computer',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '051cc8c4-84be-4278-9577-9ffd09da205a',
  'fe5987a9-2e95-4fa3-b4b2-7b79d12e1969',
  'What is the primary function of a computer program?',
  'A program provides the set of instructions the computer follows to process data.',
  'single',
  1,
  3,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '63684867-6fdb-4590-8723-078ea1ddcac4',
  '051cc8c4-84be-4278-9577-9ffd09da205a',
  'To store physical data',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'c0de6348-fa09-4b97-b242-22c280013c09',
  '051cc8c4-84be-4278-9577-9ffd09da205a',
  'To provide instructions for processing data',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '68fdca97-ca91-4ca3-8c76-7743637b4119',
  '051cc8c4-84be-4278-9577-9ffd09da205a',
  'To display output on the screen',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'c8307d60-77d4-4d2e-8ebe-9ddc44c51814',
  '051cc8c4-84be-4278-9577-9ffd09da205a',
  'To cool down the CPU',
  false,
  4
) ON CONFLICT DO NOTHING;

-- Content Item for 'Characteristics of Computers'
INSERT INTO public.content_items (id, unit_id, subject_id, topic_id, title, description, type, status, visibility)
VALUES (
  '52164477-d02d-4724-8efb-900b88c80f43',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '05968c8c-2a26-4933-a021-e457681771fc',
  '53857dd5-db47-4d92-8f57-55e41440d739',
  'Characteristics of Computers - Notes',
  'Comprehensive study material for Characteristics of Computers',
  'note',
  'published',
  'public'
) ON CONFLICT DO NOTHING;

-- Note for 'Characteristics of Computers'
INSERT INTO public.notes (id, unit_id, topic_id, title, slug, body, status, visibility, summary, sort_order)
VALUES (
  '664f94df-5e5d-4bbf-a75e-29e94572cf43',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '53857dd5-db47-4d92-8f57-55e41440d739',
  'Characteristics of Computers - Full Notes',
  'characteristics-of-computers-full-notes',
  '
# Characteristics of Computers

## Learning Objectives
- Identify the key characteristics that make computers indispensable.
- Understand the concepts of speed, accuracy, diligence, versatility, and memory.

## Introduction
The rapid adoption of computers across all sectors of society is due to their powerful characteristics. They are not just fast calculators; they possess unique attributes that allow them to perform complex tasks flawlessly over extended periods.

## Core Concepts
The defining traits of modern computing systems include:
1. **Speed**: Performing millions of instructions per second.
2. **Accuracy**: Executing instructions precisely as written.
3. **Diligence**: Working continuously without fatigue.
4. **Versatility**: Adapting to completely different tasks.
5. **Memory**: Storing and retrieving data on demand.

## Important Definitions
- **GIGO (Garbage In, Garbage Out)**: A concept stating that flawed, or nonsense input data produces nonsense output.
- **Microsecond**: One-millionth of a second ($10^{-6}$).
- **Nanosecond**: One-billionth of a second ($10^{-9}$).

## Detailed Explanation
A computer''s effectiveness stems from its combination of speed and accuracy. While humans might make calculation errors when fatigued, a computer exhibits **diligence**, meaning it performs repetitive tasks with the exact same precision on the millionth iteration as it did on the first. 

Furthermore, computers are highly **versatile**. A single machine can route network traffic, render video game graphics, and calculate complex spreadsheets simply by loading different software. 

Finally, a computer possesses **memory** or storage capacity. Unlike human memory, which can fade or alter over time, digital storage retains data exactly as it was written until it is intentionally deleted, overwritten, or compromised by hardware failure. This allows for massive amounts of information to be reliably retrieved at a later date.

## Examples
- **Speed**: Weather forecasting systems analyzing millions of data points in seconds.
- **Versatility**: A smartphone acting as a camera, a calculator, a web browser, and a phone.
- **Accuracy**: Banking software correctly transferring exact funds without mathematical error.

## Key Points
- Speed is measured in fractions of a second (micro/nano/pico-seconds).
- Accuracy is dependent on correct input (GIGO).
- Diligence ensures consistent performance without human fatigue.
- Memory allows precise storage and retrieval of digital information.

## Quick Revision
Computers are fast (speed), correct (accuracy), tireless (diligence), multi-purpose (versatility), and capable of retaining data reliably (memory).

## Practice Questions
1. Elaborate on the ''Diligence'' and ''Versatility'' characteristics of a computer.
2. What does GIGO stand for, and how does it relate to computer accuracy?
3. Explain how computer memory differs from human memory in terms of data retrieval.
',
  'published',
  'public',
  'Study notes covering Characteristics of Computers',
  1
) ON CONFLICT DO NOTHING;

-- Quiz for 'Characteristics of Computers'
INSERT INTO public.quizzes (id, unit_id, topic_id, title, slug, description, status, is_public, max_attempts, passing_pct, order_index, negative_marking)
VALUES (
  '9332c78e-19df-4317-857d-2ffea5851d13',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '53857dd5-db47-4d92-8f57-55e41440d739',
  'Quiz: Characteristics of Computers',
  'quiz-characteristics-of-computers',
  'Assess your understanding of the core characteristics that define modern computers.',
  'published',
  true,
  10,
  40,
  1,
  false
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'c1e0cdf5-623b-4ea0-806d-e7726c47a83e',
  '9332c78e-19df-4317-857d-2ffea5851d13',
  'The term GIGO (Garbage In, Garbage Out) is related to which characteristic of computers?',
  'GIGO relates to accuracy. The computer produces accurate output as long as the input and instructions are accurate.',
  'single',
  1,
  1,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'f591f122-4085-42d9-ae0a-c0d30501c815',
  'c1e0cdf5-623b-4ea0-806d-e7726c47a83e',
  'Speed',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '7ce291cb-5213-4d70-959d-ae62eef599c4',
  'c1e0cdf5-623b-4ea0-806d-e7726c47a83e',
  'Accuracy',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'bd090988-6449-4dd2-aaf5-1ecebab31095',
  'c1e0cdf5-623b-4ea0-806d-e7726c47a83e',
  'Diligence',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '356ef784-7012-41f7-b1d0-54a92213a8d1',
  'c1e0cdf5-623b-4ea0-806d-e7726c47a83e',
  'Versatility',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '88717ad7-7698-40fe-8a7a-1ab9bc1f42ae',
  '9332c78e-19df-4317-857d-2ffea5851d13',
  'Which characteristic means that a computer is free from tiredness and lack of concentration?',
  'Diligence refers to the computer''s ability to perform repetitive tasks without losing focus or experiencing fatigue.',
  'single',
  1,
  2,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '248db363-f6df-4cce-95c6-2a6d0321651c',
  '88717ad7-7698-40fe-8a7a-1ab9bc1f42ae',
  'Versatility',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '217e0fb2-84ea-452b-8a84-5c7cd3261cd9',
  '88717ad7-7698-40fe-8a7a-1ab9bc1f42ae',
  'Diligence',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '6d6da6f4-ee22-4a44-8035-1664ac290add',
  '88717ad7-7698-40fe-8a7a-1ab9bc1f42ae',
  'Memory',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '879986a1-76c7-46b0-ac6c-cb0e0615e0a7',
  '88717ad7-7698-40fe-8a7a-1ab9bc1f42ae',
  'Automation',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '1a2d3469-4674-4c29-b96a-b2341d25c647',
  '9332c78e-19df-4317-857d-2ffea5851d13',
  'A computer''s ability to perform completely different types of tasks one after another is called:',
  'Versatility is the ability of a computer to adapt to many different functions or activities.',
  'single',
  1,
  3,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '44ebee3e-7bda-4577-882e-84391ce47faf',
  '1a2d3469-4674-4c29-b96a-b2341d25c647',
  'Versatility',
  true,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '71da78ea-d39d-47d1-bded-78330e8829f3',
  '1a2d3469-4674-4c29-b96a-b2341d25c647',
  'Diligence',
  false,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '699150e8-f56c-4ba2-971f-558b19e2bd99',
  '1a2d3469-4674-4c29-b96a-b2341d25c647',
  'Reliability',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '854e970d-4a77-4361-bfe4-d1a974c07750',
  '1a2d3469-4674-4c29-b96a-b2341d25c647',
  'Accuracy',
  false,
  4
) ON CONFLICT DO NOTHING;

-- Content Item for 'Generations of Computers'
INSERT INTO public.content_items (id, unit_id, subject_id, topic_id, title, description, type, status, visibility)
VALUES (
  '44da81f4-fce9-4d3a-b718-73c9b5ddb5d2',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '05968c8c-2a26-4933-a021-e457681771fc',
  '66e861e7-63c0-4c1d-b0a0-ad099e223e15',
  'Generations of Computers - Notes',
  'Comprehensive study material for Generations of Computers',
  'note',
  'published',
  'public'
) ON CONFLICT DO NOTHING;

-- Note for 'Generations of Computers'
INSERT INTO public.notes (id, unit_id, topic_id, title, slug, body, status, visibility, summary, sort_order)
VALUES (
  '04b3bc1f-1184-4a22-ab55-3c301acfc45f',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '66e861e7-63c0-4c1d-b0a0-ad099e223e15',
  'Generations of Computers - Full Notes',
  'generations-of-computers-full-notes',
  '
# Generations of Computers

## Learning Objectives
- Trace the historical evolution of computers.
- Identify the key electronic components that define traditional generations.
- Understand how physical size, speed, and capabilities improved over time.

## Introduction
The history of computer hardware development is traditionally taught by dividing it into distinct "generations." Each of these generations is characterized by a major technological shift in the core electronic components that fundamentally changed the way computers operate.

## Core Concepts
The traditional textbook classification outlines five generations:
1. **First Generation**: Defined by Vacuum Tubes.
2. **Second Generation**: Defined by Transistors.
3. **Third Generation**: Defined by Integrated Circuits (ICs).
4. **Fourth Generation**: Defined by Microprocessors.
5. **Fifth Generation**: Associated with Artificial Intelligence and advanced parallel processing.

## Important Definitions
- **Vacuum Tube**: An early electronic device that controlled electric current through a vacuum in a sealed glass container.
- **Transistor**: A semiconductor device used to amplify or switch electrical signals, replacing vacuum tubes.
- **Integrated Circuit (IC)**: A set of electronic circuits on one small flat piece of semiconductor material (silicon).
- **Microprocessor**: A computer processor where the data processing logic and control is included on a single integrated circuit.

## Detailed Explanation

### First Generation (approx. 1940s - 1950s)
Early computers like the ENIAC and UNIVAC relied on **vacuum tubes** for circuitry and magnetic drums for memory. These machines were enormous, filling entire rooms. They consumed vast amounts of electricity, generated significant heat, and experienced frequent hardware failures.

### Second Generation (approx. late 1950s - mid 1960s)
The invention of the **transistor** revolutionized computing. Transistors were much smaller, faster, cheaper, and more reliable than vacuum tubes. This era also saw the transition from binary machine language to symbolic assembly languages, making programming slightly easier.

### Third Generation (approx. mid 1960s - early 1970s)
Transistors were miniaturized and placed on silicon chips, creating **Integrated Circuits (ICs)**. This drastically reduced the physical size of computers while increasing their processing power. Users interacted with these computers using keyboards and monitors rather than punched cards, and early operating systems allowed multiple applications to run.

### Fourth Generation (approx. 1970s onwards)
The development of the **Microprocessor** brought thousands of integrated circuits onto a single silicon chip. What used to take up an entire room could now fit on a desk, leading to the rise of Personal Computers (PCs). This era popularized graphical user interfaces (GUIs), the mouse, and eventually the internet.

### Fifth Generation (Conceptual / Modern Era)
In academic contexts, the fifth generation is often characterized by the integration of **Artificial Intelligence (AI)**, ultra-large-scale integration (ULSI), and parallel processing. Technologies like machine learning, natural language processing, and quantum computing represent the aspirations of this advanced computing paradigm.

## Examples
- **First Generation**: ENIAC (Electronic Numerical Integrator and Computer).
- **Second Generation**: IBM 1620.
- **Third Generation**: IBM 360 series.
- **Fourth Generation**: Early Apple Macintosh and IBM PCs.

## Key Points
- As generations progressed, physical size and power consumption decreased.
- Concurrently, processing speed, memory capacity, and reliability increased exponentially.
- The shift from vacuum tubes to solid-state silicon (transistors and ICs) is the most critical turning point in computer history.

## Quick Revision
Vacuum Tubes $\rightarrow$ Transistors $\rightarrow$ Integrated Circuits $\rightarrow$ Microprocessors $\rightarrow$ AI & Parallel Processing.

## Practice Questions
1. Explain the primary technological difference between first and second-generation computers.
2. What role did the Integrated Circuit play in the physical evolution of computers?
3. Discuss the traditional characteristics associated with fifth-generation computing.
',
  'published',
  'public',
  'Study notes covering Generations of Computers',
  1
) ON CONFLICT DO NOTHING;

-- Quiz for 'Generations of Computers'
INSERT INTO public.quizzes (id, unit_id, topic_id, title, slug, description, status, is_public, max_attempts, passing_pct, order_index, negative_marking)
VALUES (
  '4e1eff71-31d3-4d6b-b8d4-9ecf593a826d',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '66e861e7-63c0-4c1d-b0a0-ad099e223e15',
  'Quiz: Generations of Computers',
  'quiz-generations-of-computers',
  'Test your knowledge of the historical evolution of computer technology.',
  'published',
  true,
  10,
  40,
  1,
  false
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'df3d5c8a-fd2a-401a-8f3c-b1a7d568f258',
  '4e1eff71-31d3-4d6b-b8d4-9ecf593a826d',
  'Which electronic component was primarily used in First Generation computers?',
  'First-generation computers relied on vacuum tubes for circuitry.',
  'single',
  1,
  1,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '9539ee32-0ac8-4e45-89aa-fcc3828803c2',
  'df3d5c8a-fd2a-401a-8f3c-b1a7d568f258',
  'Transistors',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '23c45661-dd97-4d2f-8d30-b624610b183b',
  'df3d5c8a-fd2a-401a-8f3c-b1a7d568f258',
  'Vacuum Tubes',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'c8bdb962-6c47-40c7-a2a9-59e0aca00b52',
  'df3d5c8a-fd2a-401a-8f3c-b1a7d568f258',
  'Integrated Circuits',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'f83f9310-b706-4590-b978-2c30625bf493',
  'df3d5c8a-fd2a-401a-8f3c-b1a7d568f258',
  'Microprocessors',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'ac84e2f8-4329-4852-a5ea-ed1b675fff4a',
  '4e1eff71-31d3-4d6b-b8d4-9ecf593a826d',
  'The invention of the Integrated Circuit (IC) defined which generation of computers in traditional classification?',
  'Third-generation computers were characterized by the use of Integrated Circuits.',
  'single',
  1,
  2,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '00a51821-2f0b-48d4-9209-a42967a55d5d',
  'ac84e2f8-4329-4852-a5ea-ed1b675fff4a',
  'Second Generation',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '53d119a0-3f7e-47e4-9d43-65b7d9db7d4d',
  'ac84e2f8-4329-4852-a5ea-ed1b675fff4a',
  'Third Generation',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '78cb66b3-2cd3-43cb-8349-c2d460239bc7',
  'ac84e2f8-4329-4852-a5ea-ed1b675fff4a',
  'Fourth Generation',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '753dd52d-e4bc-4e1c-83e7-afc07756a83f',
  'ac84e2f8-4329-4852-a5ea-ed1b675fff4a',
  'Fifth Generation',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'afef21aa-38e8-4dc7-9af5-2472c9081dc0',
  '4e1eff71-31d3-4d6b-b8d4-9ecf593a826d',
  'In textbook classifications, Artificial Intelligence and advanced parallel processing are most closely associated with which computer generation?',
  'The fifth generation concept focuses on AI and advanced hardware technologies.',
  'single',
  1,
  3,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '057d8694-d0e5-4a56-be1b-00121a0e80c4',
  'afef21aa-38e8-4dc7-9af5-2472c9081dc0',
  'Third Generation',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '798ff861-0067-40bd-8a95-2b847be3d240',
  'afef21aa-38e8-4dc7-9af5-2472c9081dc0',
  'Fourth Generation',
  false,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '38bb4666-a26a-4515-bc69-e30d1c4ada8c',
  'afef21aa-38e8-4dc7-9af5-2472c9081dc0',
  'Fifth Generation',
  true,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '6332a0bb-d6ac-433c-a5fe-4dfc361c65bb',
  'afef21aa-38e8-4dc7-9af5-2472c9081dc0',
  'Second Generation',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '2b56814a-7f2e-4f77-9964-8879826f57ce',
  '4e1eff71-31d3-4d6b-b8d4-9ecf593a826d',
  'ENIAC is an example of a computer from which generation?',
  'ENIAC (Electronic Numerical Integrator and Computer) was one of the earliest first-generation computers.',
  'single',
  1,
  4,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'ee6f9839-4e9f-4ab0-8d25-6863b4b1ab4f',
  '2b56814a-7f2e-4f77-9964-8879826f57ce',
  'First Generation',
  true,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '2c8d22ab-eab6-4750-a98c-7b6f05a76cc9',
  '2b56814a-7f2e-4f77-9964-8879826f57ce',
  'Second Generation',
  false,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '5019cd4b-d275-424d-b9c6-87122a9d2d8e',
  '2b56814a-7f2e-4f77-9964-8879826f57ce',
  'Third Generation',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '34312319-5ff3-4fb2-a692-76b059f21bc5',
  '2b56814a-7f2e-4f77-9964-8879826f57ce',
  'Fourth Generation',
  false,
  4
) ON CONFLICT DO NOTHING;

-- Content Item for 'Types of Computers'
INSERT INTO public.content_items (id, unit_id, subject_id, topic_id, title, description, type, status, visibility)
VALUES (
  '124c0e5a-04ca-4286-8d84-753e7263b4cf',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '05968c8c-2a26-4933-a021-e457681771fc',
  '341e7464-38df-4e6a-9348-3b494632d8f0',
  'Types of Computers - Notes',
  'Comprehensive study material for Types of Computers',
  'note',
  'published',
  'public'
) ON CONFLICT DO NOTHING;

-- Note for 'Types of Computers'
INSERT INTO public.notes (id, unit_id, topic_id, title, slug, body, status, visibility, summary, sort_order)
VALUES (
  '92b4167c-a105-4dff-a16d-f1a3f0ce7d6f',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '341e7464-38df-4e6a-9348-3b494632d8f0',
  'Types of Computers - Full Notes',
  'types-of-computers-full-notes',
  '
# Types of Computers

## Learning Objectives
- Classify computers based on their operating principles (Data Handling).
- Classify computers based on their historical size and processing capability.

## Introduction
Computers come in various sizes, shapes, and functionalities. To better understand the landscape of computing devices, they are broadly classified into different types based on how they process data natively, and historically by their physical size and processing power.

## Core Concepts
Computers are categorized using two main frameworks:
1. **By Data Handling**: Analog, Digital, and Hybrid.
2. **By Size/Capacity**: Microcomputers, Minicomputers, Mainframes, and Supercomputers.

## Important Definitions
- **Discrete Data**: Data that can only take specific, distinct values (like 0s and 1s).
- **Continuous Data**: Data that can take any value within a range (like temperature or fluid pressure).

## Detailed Explanation

### Classification Based on Data Handling

1. **Analog Computers**: These machines handle continuous, varying data. Instead of counting discrete numbers, they measure physical quantities (such as voltage, pressure, or rotation) and represent data via continuous signals. 
2. **Digital Computers**: These process data in discrete, binary form (0s and 1s). They are highly accurate, versatile, and represent the vast majority of computers used today (including modern desktops, laptops, and smartphones).
3. **Hybrid Computers**: These systems combine features of both analog and digital computing. They typically use analog components to measure real-world physical continuous signals and convert them into digital discrete data for complex logical processing.

### Classification Based on Size and Capacity

1. **Microcomputers**: Small, relatively inexpensive computers designed for individual use. They utilize a single microprocessor.
2. **Minicomputers**: Historically, minicomputers were mid-sized machines that filled the gap between single-user microcomputers and massive mainframes. In the 1970s and 80s, they supported multiple users simultaneously in small businesses. Today, this specific category name is mostly historical, replaced by modern mid-range servers.
3. **Mainframe Computers**: Very large, expensive, and reliable computers capable of supporting thousands of concurrent users. They are designed to handle massive amounts of transaction data with extreme stability.
4. **Supercomputers**: The fastest, most powerful computers designed specifically for calculation-intensive tasks rather than transaction processing. They employ massive parallel processing architectures.

## Examples
- **Analog**: Traditional mechanical speedometers, older analog flight simulators.
- **Hybrid**: Modern patient monitoring systems (e.g., advanced ECG machines that use analog sensors to read continuous electrical signals from the heart, and digital processors to analyze and display the results).
- **Mainframe**: Core banking systems processing thousands of ATM transactions simultaneously.
- **Supercomputer**: Systems used for simulating weather patterns, nuclear research, or molecular modeling.

## Key Points
- Digital computers count; analog computers measure.
- Hybrid systems bridge the gap between continuous real-world signals and digital logic.
- Supercomputers focus on calculation speed (FLOPs), while Mainframes focus on transactional throughput and reliability.

## Quick Revision
- **Data**: Analog (continuous), Digital (discrete), Hybrid (both).
- **Size**: Micro (personal), Mini (historical mid-range), Mainframe (enterprise transactions), Supercomputer (scientific calculations).

## Practice Questions
1. Explain how a hybrid computer differs from a purely digital computer, providing a relevant example.
2. Discuss the historical context of the "Minicomputer" category.
3. Contrast a Mainframe computer with a Supercomputer in terms of their primary use cases.
',
  'published',
  'public',
  'Study notes covering Types of Computers',
  1
) ON CONFLICT DO NOTHING;

-- Quiz for 'Types of Computers'
INSERT INTO public.quizzes (id, unit_id, topic_id, title, slug, description, status, is_public, max_attempts, passing_pct, order_index, negative_marking)
VALUES (
  '847b4322-9786-462c-981a-b502cb26bd54',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '341e7464-38df-4e6a-9348-3b494632d8f0',
  'Quiz: Types of Computers',
  'quiz-types-of-computers',
  'Evaluate your understanding of how computers are classified by size and data processing methods.',
  'published',
  true,
  10,
  40,
  1,
  false
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  'ea018e78-9b1a-422e-92b0-d199a82f2436',
  '847b4322-9786-462c-981a-b502cb26bd54',
  'A computer system that utilizes analog sensors to measure continuous physical data, but processes that data digitally, is best classified as:',
  'Hybrid computers combine analog measurement components with digital processing components.',
  'single',
  1,
  1,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '8f261e39-7e71-43e5-a582-2645dd056597',
  'ea018e78-9b1a-422e-92b0-d199a82f2436',
  'A supercomputer',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '2e9348ce-b180-4998-8528-f7be08ec0b2b',
  'ea018e78-9b1a-422e-92b0-d199a82f2436',
  'A hybrid computer',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '02482348-dc49-4b21-8be4-f04e998de119',
  'ea018e78-9b1a-422e-92b0-d199a82f2436',
  'A mainframe computer',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'f16302bd-a15b-497d-a976-802226715a24',
  'ea018e78-9b1a-422e-92b0-d199a82f2436',
  'A minicomputer',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '39456762-a39b-4e12-9ee7-038638a5cbd0',
  '847b4322-9786-462c-981a-b502cb26bd54',
  'Which type of computer is primarily designed for extremely complex scientific calculations like global weather modeling?',
  'Supercomputers possess the massive parallel processing power required for complex simulations.',
  'single',
  1,
  2,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'fbb28981-e9c0-4cc7-8b13-61e1fa3fa477',
  '39456762-a39b-4e12-9ee7-038638a5cbd0',
  'Mainframe',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '3e42d899-3b3e-4838-bc07-99db3902eb09',
  '39456762-a39b-4e12-9ee7-038638a5cbd0',
  'Supercomputer',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '14387784-ce88-4016-8cc4-093702d6707c',
  '39456762-a39b-4e12-9ee7-038638a5cbd0',
  'Minicomputer',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '217adb86-eb6f-4380-8e21-7ed37c62ed71',
  '39456762-a39b-4e12-9ee7-038638a5cbd0',
  'Microcomputer',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '214da8d2-f5f0-42da-91c7-d1fa197bf4b0',
  '847b4322-9786-462c-981a-b502cb26bd54',
  'A standard modern desktop PC or laptop falls under which historical classification category?',
  'Desktop PCs and laptops are designed for individual use using a microprocessor, classifying them as microcomputers.',
  'single',
  1,
  3,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '8cf8979b-80e4-47e5-bbbc-32f7e0b172b1',
  '214da8d2-f5f0-42da-91c7-d1fa197bf4b0',
  'Minicomputer',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '7af00bcd-7a8c-430f-b216-bde3e478c0ba',
  '214da8d2-f5f0-42da-91c7-d1fa197bf4b0',
  'Microcomputer',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'c6ab5c63-d356-43b1-ab7d-84cbf01f4294',
  '214da8d2-f5f0-42da-91c7-d1fa197bf4b0',
  'Mainframe',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'a6a2bdef-565a-479d-9d31-c55030212c7f',
  '214da8d2-f5f0-42da-91c7-d1fa197bf4b0',
  'Hybrid computer',
  false,
  4
) ON CONFLICT DO NOTHING;

-- Content Item for 'Applications of Computers'
INSERT INTO public.content_items (id, unit_id, subject_id, topic_id, title, description, type, status, visibility)
VALUES (
  'd16f0c5a-4b75-414f-9686-1711b09b506a',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '05968c8c-2a26-4933-a021-e457681771fc',
  '7513ac8b-2003-4899-999c-b98fa43baf12',
  'Applications of Computers - Notes',
  'Comprehensive study material for Applications of Computers',
  'note',
  'published',
  'public'
) ON CONFLICT DO NOTHING;

-- Note for 'Applications of Computers'
INSERT INTO public.notes (id, unit_id, topic_id, title, slug, body, status, visibility, summary, sort_order)
VALUES (
  '68f10693-5d29-4cd9-a4ce-edc197c5cec2',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '7513ac8b-2003-4899-999c-b98fa43baf12',
  'Applications of Computers - Full Notes',
  'applications-of-computers-full-notes',
  '
# Applications of Computers

## Learning Objectives
- Explore the diverse fields where computers are heavily utilized.
- Understand the specific roles computers play in education, business, healthcare, and science.
- Analyze the impact of computerization on daily workflows.

## Introduction
In the modern era, computers have permeated almost every aspect of human life. They have transformed from specialized military and scientific calculators into universal tools that drive how we work, learn, communicate, and entertain ourselves.

## Core Concepts
The integration of computers across various domains relies on three primary capabilities:
1. **Rapid Data Processing**: Automating repetitive tasks quickly.
2. **Massive Data Storage**: Organizing and retrieving large datasets safely.
3. **Global Connectivity**: Facilitating instantaneous communication.

## Important Definitions
- **CBT (Computer-Based Training)**: Any course of learning that encompasses the use of computers in both instruction and management of the teaching and learning process.
- **CAD/CAM (Computer-Aided Design / Computer-Aided Manufacturing)**: Software used by architects, engineers, and manufacturers to design and manufacture products precisely.

## Detailed Explanation

### 1. Education
Computers are transforming classrooms and self-study. They facilitate online learning (E-learning) and provide vast repositories of information via the internet. Educational institutions also rely on computers to maintain student records, schedule classes, and process examination results efficiently.

### 2. Business and Finance
Modern businesses depend heavily on computers for daily operations. This includes payroll processing, accounting, and inventory management. The banking sector has been entirely revolutionized; ATMs, online banking portals, and electronic fund transfers (like NEFT and RTGS) rely on secure, interconnected computer networks.

### 3. Healthcare and Medicine
In the medical field, computers save lives and improve care. They are used for maintaining Electronic Health Records (EHRs), allowing instant access to patient histories. Complex diagnostic imaging techniques like CT scans and MRIs are entirely dependent on computer processing to construct readable images. Additionally, computers monitor vital signs in ICUs and assist surgeons in robotic surgeries.

### 4. Science and Engineering
Scientists and engineers use computers for complex tasks that would be otherwise impossible. CAD software allows for the precise 3D modeling of buildings, cars, and airplane components before they are built. Supercomputers run complex mathematical models to simulate weather patterns, track space probes, and conduct genetic sequencing.

### 5. Government, Defense, and Entertainment
Governments use computers to maintain massive citizen databases, process tax records, and manage census data. In defense, computers control sophisticated radar, secure communications, and missile tracking systems. Meanwhile, the entertainment industry utilizes powerful computers for rendering Computer Generated Imagery (CGI) in films and processing realistic physics in video games.

## Examples
- **Healthcare**: Using software to cross-reference a patient''s new prescription against their known allergies.
- **Business**: E-commerce platforms automatically adjusting inventory levels when a customer makes a purchase.
- **Science**: Simulating the aerodynamic drag of a new car design using CAD software.

## Key Points
- Computers are universal tools applicable in almost every industry.
- Key impacts include automation of labor, secure data storage, and global communication.
- Complex industries like modern healthcare and engineering are heavily dependent on computer processing.

## Quick Revision
Applications span Education (CBT), Business (accounting/ATMs), Healthcare (MRI/EHR), Engineering (CAD/CAM), and Government/Defense.

## Practice Questions
1. Describe how computers are utilized in the healthcare sector, providing specific examples.
2. Explain the term CAD/CAM and its significance in engineering and manufacturing.
3. Discuss the impact of computers on modern banking systems.
',
  'published',
  'public',
  'Study notes covering Applications of Computers',
  1
) ON CONFLICT DO NOTHING;

-- Quiz for 'Applications of Computers'
INSERT INTO public.quizzes (id, unit_id, topic_id, title, slug, description, status, is_public, max_attempts, passing_pct, order_index, negative_marking)
VALUES (
  '91a015ce-e033-4f36-b1bc-903aa343626c',
  '0985c212-df92-48df-8412-93e7de4c34c8',
  '7513ac8b-2003-4899-999c-b98fa43baf12',
  'Quiz: Applications of Computers',
  'quiz-applications-of-computers',
  'Test your knowledge of the various ways computers are used in different industries.',
  'published',
  true,
  10,
  40,
  1,
  false
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '0d22f7b3-a067-4daa-bd04-eb3c6ef20832',
  '91a015ce-e033-4f36-b1bc-903aa343626c',
  'What does CAD stand for in the context of engineering and design?',
  'CAD stands for Computer-Aided Design, used extensively by engineers and architects to draft designs.',
  'single',
  1,
  1,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'ffd66d53-0e8b-469b-a7c0-49904ac678dc',
  '0d22f7b3-a067-4daa-bd04-eb3c6ef20832',
  'Computer Algorithm Design',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '64de954c-8f9e-4472-9e49-cf94c93c7e5a',
  '0d22f7b3-a067-4daa-bd04-eb3c6ef20832',
  'Computer-Aided Design',
  true,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '60d53af2-b62f-4dbd-b490-697a7fd3b23b',
  '0d22f7b3-a067-4daa-bd04-eb3c6ef20832',
  'Calculation And Drafting',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'c4ed3405-c512-4dbc-b804-b5d7012d6077',
  '0d22f7b3-a067-4daa-bd04-eb3c6ef20832',
  'Computer Architecture Diagram',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '8c0b3cef-c320-4d6e-9659-82c6329adf56',
  '91a015ce-e033-4f36-b1bc-903aa343626c',
  'Which of the following represents a primary application of computers in the banking sector?',
  'ATMs (Automated Teller Machines) and secure online transaction processing rely entirely on interconnected computer networks.',
  'single',
  1,
  2,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'cc6a1433-62d0-4562-8c7a-bee45cb13206',
  '8c0b3cef-c320-4d6e-9659-82c6329adf56',
  'Diagnostic Imaging (MRI)',
  false,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '63d9daf3-c84c-4d7a-9e88-b93997a7f6fa',
  '8c0b3cef-c320-4d6e-9659-82c6329adf56',
  'Weather Forecasting',
  false,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '94ddaa67-7608-4cdb-a7e7-8915b87c25af',
  '8c0b3cef-c320-4d6e-9659-82c6329adf56',
  'Operating ATMs and processing transactions',
  true,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'd1371cc4-ab0c-4ba5-8bad-64e0ceaefe6c',
  '8c0b3cef-c320-4d6e-9659-82c6329adf56',
  'Rendering Computer Generated Imagery (CGI)',
  false,
  4
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, prompt, explanation, type, points, order_index, negative_marks)
VALUES (
  '0385cc2e-2b97-44be-b3a6-fdcc4074694b',
  '91a015ce-e033-4f36-b1bc-903aa343626c',
  'The use of computers to deliver instruction and learning materials in the education sector is often referred to by which acronym?',
  'CBT (Computer-Based Training) represents the application of computers in delivering instructional content.',
  'single',
  1,
  3,
  0
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '23d18b60-f424-487f-a05d-f7ae45dc47b3',
  '0385cc2e-2b97-44be-b3a6-fdcc4074694b',
  'CBT',
  true,
  1
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'c5e48516-eb1b-49e0-b6d8-0b8c6f5a6cf3',
  '0385cc2e-2b97-44be-b3a6-fdcc4074694b',
  'CAD',
  false,
  2
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  '759ab5d5-ed48-4c90-9b99-3860e3f3e321',
  '0385cc2e-2b97-44be-b3a6-fdcc4074694b',
  'CGI',
  false,
  3
) ON CONFLICT DO NOTHING;

INSERT INTO public.quiz_options (id, question_id, text, is_correct, order_index)
VALUES (
  'a5fa674d-38fa-41a1-a5b0-388d7c3c2378',
  '0385cc2e-2b97-44be-b3a6-fdcc4074694b',
  'RTGS',
  false,
  4
) ON CONFLICT DO NOTHING;

COMMIT;
